### ISSUE TITLE
 How to get the cycles of ARM Cortex-M while GIFT  program is executed?

### ISSUE THREAD

**Issue by BreezyEvening** [aadomn/gift#2]
Hello ，can you tell me how to get the cycles of ARM Cortex-M while GIFT  program is executed?( In paper" A New GIFT Representation Fast Constant-Time Implementations of GIFT and GIFT-COFB on ARM Cortex-M",Table 4).Thank you very much!!!

**Comment by aadomn** [comment]
Hi, thanks for your interest in our GIFT implementations.
The results reported in the paper were obtained by using the `DWT_CYCCNT` cycle counter register.
We simply read the counter after and before the function to benchmark, just as done in the following example: https://github.com/joostrijneveld/STM32-getting-started/blob/master/common/cyclecount.c
If you are using an advanced IDE, then it might also come with some integrated tools to measure the clock cycles.
Note that our results were obtained with a clock frequency set to 24MHz.
